name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # You can specify other versions if needed

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    # - run: npm run test  # Ensure you have a test script in your package.json or remove this line

    # Deployment to Heroku
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'  # This ensures we only deploy on pushes to the main branch
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku main
